# Generated by Django 4.2.1 on 2023-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('country', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.CharField(),
        ),
    ]
