# Generated by Django 4.2.1 on 2023-06-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_alter_brand_country_alter_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=20)),
                ('size', models.BigIntegerField()),
                ('flavour', models.CharField(max_length=20)),
                ('grams_of_protein', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
