# Generated by Django 4.2.1 on 2023-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_bcaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('brand', models.CharField(max_length=20)),
                ('size', models.BigIntegerField()),
                ('flavour', models.CharField(max_length=20)),
                ('grams_of_protein', models.IntegerField()),
                ('sugarfree', models.BooleanField()),
            ],
        ),
    ]
